config/routes.rb
# Rails.application.routes.draw do
  
#   root to: 'about#about'
#   devise_for :users
#   resources :user

# end

Rails.application.routes.draw do

  namespace :admins do
    
    get '/home', to: 'home#index'
    get "/skills", to: "skills#index"
    get '/projects', to: 'projects#index'
    get '/contact', to: 'contact#index'
    
  end
  
  root to: 'about#about'
  devise_for :user

  get '/home', to: 'home#index'
  get '/skills', to: 'skills#index'
  get '/projects', to: 'projects#index'
  get '/contact', to: 'contact#index'


  # get "/skills", to: "skills#index"
  get "send" => 'send#index'
  post "send" => 'send#create'


  # config/routes.rb
  Rails.application.routes.draw do
  resources :students, only: [:show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  # before_action :authenticate_user!
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end
    
    def create
      # @params = params
      # ContactMailer.contact_send(params).deliver
      # flash[:notice] = 'mensaje enviado'
      # redirect_to send_path


      def create
        @params = params.new(params[:params])
    
        respond_to do |format|
          if @params.save
            # Tell the paramsMailer to send a welcome email after save
            paramsMailer.with(params: @params).welcome_email.deliver_later
    
            format.html { redirect_to(@params, notice: 'params was successfully created.') }
            format.json { render json: @params, status: :created, location: @params }
          else
            format.html { render action: 'new' }
            format.json { render json: @params.errors, status: :unprocessable_entity }
          end
        end
      end
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
      
    end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def index
        
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins/contact_helper.rb
module Admins::ContactHelper
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/admins/skills_helper.rb
module Admins::SkillsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def is_admin_in
        request.fullpath.include?("admins")
    end

end

app/helpers/contact_helper.rb
module ContactHelper
    def contact_send(params)
      @parameters = params
      mail(to: "wgonzalezw@fwdcostarica.com", subject: @parameters[:subject])
    end
  end

app/helpers/habilidades_helper.rb
module HabilidadesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/menu/_navbar.html.erb
<header>

    <nav>

        <% if is_admin_in %>

            <ul class="navbar">

                <li class="options">
                    <%= link_to "About us", admins_home_path %>
                </li>

                <li class="options">
                    <%= link_to "Skills", admins_skills_path %>
                </li>

                <li class="options">
                    <%= link_to "Projects", admins_projects_path %>
                </li>

                <li class="options">
                    <%= link_to "Contact", admins_contact_path %>
                </li>
                
            </ul>

        <% else %>

            <ul class="navbar">

                <li class="options">
                    <%= link_to "About us", home_path %>
                </li>

                <li class="options">
                    <%= link_to "Skills", skills_path %>
                </li>

                <li class="options">
                    <%= link_to "Projects", projects_path %>
                </li>

                <li class="options">
                    <%= link_to "Contact", contact_path %>
                </li>
                
            </ul>

        <% end %>

        
    </nav>
    
    <br>

</header>